//
// UserApi.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public class UserApi : NSObject, Mappable {
	var balance : Int = 0
	var firstName : String?
	var lastName : String?
	var authUserId : String?
    var userId : String?
    var _id : String?
    var isBot : Bool = false
	var createdDateTime : Double = Date().timeIntervalSince1970
    var createdDateTimeStamp : Double = Date().timeIntervalSince1970
    var saleDurationPresetMins : Int = 0
    var bidDurationPresetMins : Int = 0

    public class func newInstance(_ map: Map) -> Mappable? {
        return UserApi()
    }
    public required init?(map: Map){}
    public override init(){}

	public func mapping(map: Map) {
		balance <- map["balance"]
		firstName <- map["firstName"]
		lastName <- map["lastName"]
		authUserId <- map["authUserId"]
        userId <- map["userId"]
        _id <- map["id"]
        isBot <- map["isBot"]
		createdDateTime <- map["createdDateTime._seconds"]
        createdDateTimeStamp <- map["createdDateTimeStamp"]
        saleDurationPresetMins <- map["saleDurationPresetMins"]
        bidDurationPresetMins <- map["bidDurationPresetMins"]
	}
}

extension UserApi {
    public var id: String {
        return _id ?? authUserId ?? userId ?? ""
    }
}
