opt_in_rules: # some rules are only opt-in

included:

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests
  - Example
  - Sources
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - empty_count
  - redundant_nil_coalescing
  - switch_case_on_newline
  - force_unwrapping
  - conditional_returns_on_newline
  - closure_spacing
  - implicitly_unwrapped_optional
  - sorted_imports
  - valid_docs
  - nslocalizedstring_require_bundle